### ISSUE TITLE
How can reduce live video latency?

### ISSUE THREAD

**Issue by MinChanSike** [kevinGodell/mse-live-player#3]

**Comment by kevinGodell** [comment]
There are a couple things that can be tried, but realistically I never get better than 2.5 seconds delay behind realtime. I am not sure what your goal is for latency, but using the browser with this video streaming type can never be *realtime*. You would probably have to use an app like vlc to be *almost* live.

The first thing that would help is to tune the ip camera so that it uses a small iframe interval or gop so that it produces shorter segments. The lowest I ever see is 2 seconds duration of segments output from my cameras. 

When using ffmpeg and doing a `-c:v copy`, it is simply copying the video and just pushing it to a new container (fragmented mp4). We have to wait the amount of time it takes for ffmpeg to find a complete segment and pushes it out. Unfortunately, that is where we **lose time** and **fall behind realtime**. This technique uses the least cpu power when compared to transcoding. 

If you are transcoding the video by using `-c:v libx264`, then you can tweak the settings so that ffmpeg creates smaller segments which it can push out sooner and therefore be closer to realtime. The problem with technique is that ffmpeg will be running hot and using alot of cpu power to transcode the video.

Check out my app where I have incorporated the mse live player and you can see which settings I use to tweak the ffmpeg params. I made it to test side by side comparisons of some different types of streaming. The player with the least delay is the jpeg via socket.io, but of course that will have no audio capabilities.

I have incorporated the mse into [ffmpeg-streamer](https://github.com/kevinGodell/ffmpeg-streamer) in action at [http://kevin.shinobi.video:3000/](http://kevin.shinobi.video:3000/)
